-- Chay file nay trong Supabase > SQL Editor
create table if not exists users (
  maNguoiDung bigint generated by default as identity primary key,
  hoTen text not null,
  email text not null unique,
  matKhau text not null,
  vaiTro text not null default 'ROLE_BUYER' check (vaiTro in ('ROLE_BUYER','ROLE_STAFF','ROLE_ADMIN'))
);
create table if not exists menu_items (
  maMon bigint generated by default as identity primary key,
  tenMon text not null,
  donGia numeric(12,2) not null,
  moTa text default '',
  hinhAnh text default '',
  trangThai text not null default 'CON_HANG' check (trangThai in ('CON_HANG','HET_HANG','DA_XOA'))
);
create table if not exists orders (
  maDonHang bigint generated by default as identity primary key,
  maNguoiDung bigint not null references users(maNguoiDung),
  maDonRutGon text not null,
  ngayDat timestamptz not null,
  thoiGianNhan timestamptz,
  trangThai text not null,
  tongTien numeric(12,2) not null default 0,
  maQr text,
  thoiHanThanhToan timestamptz
);
create table if not exists order_items (
  id bigint generated by default as identity primary key,
  maDonHang bigint not null references orders(maDonHang) on delete cascade,
  maMon bigint not null,
  tenMon text not null,
  soLuong integer not null,
  donGia numeric(12,2) not null
);

insert into users (hoTen,email,matKhau,vaiTro) values
('Quan ly Canteen','admin@uongbigo.vn','e86f78a8a3caf0b60d8e74e5942aa6d86dc150cd3c03338aef25b7d2d7e3acc7','ROLE_ADMIN'),
('Nhan vien bep','bep@uongbigo.vn','671989e46cd483c5235eeb3e278f13139bcbc7d3d23dcac19a583190d4b04ee5','ROLE_STAFF'),
('Sinh vien Demo','sv@uongbigo.vn','471425fac023b25a0f81aaac21cc5cfc6ccb9203c732105f818ae2c84836ddf3','ROLE_BUYER')
on conflict (email) do nothing;
insert into menu_items (tenMon,donGia,moTa,hinhAnh,trangThai)
select * from (values
('Com tam suon bi',32000,'Com tam suon nuong, bi, cha, trung op la','', 'CON_HANG'),
('Bun cha Ha Noi',30000,'Bun, cha nuong than hoa, nuoc mam chua ngot','', 'CON_HANG'),
('Pho bo tai',35000,'Pho bo truyen thong, nuoc dung ninh xuong','', 'CON_HANG'),
('Bun dau mam tom',28000,'Bun, dau ran, cha com, mam tom nguyen chat','', 'HET_HANG'),
('Mi xao hai san',33000,'Mi xao gion cung tom, muc, rau cu','', 'CON_HANG'),
('Salad uc ga',29000,'Uc ga ap chao, rau xa lach, sot me rang','', 'CON_HANG')
) as v(tenMon,donGia,moTa,hinhAnh,trangThai)
where not exists (select 1 from menu_items);
